### ISSUE TITLE
new site todo list

### ISSUE THREAD

**Issue by emptymalei** [JuliaQuantum/JuliaQuantum.github.io#14]
A new site has been pushed to `dev-jekyll` branch.

These are the source files with html site generated inside `_site` folder. Plz **keep the source files there**, use `jekyll build` to build the site and move everything in `_site` folder to master branch whenever the items in this todo list are all checked.

**A todo list**

- [x] Write your `README.md`
- [x] Check the `LICENSE.md` and make sure you have got the right license for this project
- [x] Place your words in these files: `index.md`, `404.md`, `project/index.md`, `news/index.html`,  `feed.xml`
- [x] Change the logo files `includes/logo.svg`, `assets/logo.png`(actually a banner logo), `favicon.ico`
- [x] **news** posts are generated from `news/posts` folder. Notice that [jekyll requires a certain format](http://jekyllrb.com/docs/posts/#creating-post-files) for the post source files.
- [x] Modify links by change `_includes/links.html`
- [x] All done?

**Comment by i2000s** [comment]
* On the top list, these have been finished: 

    - [x] `README.md`.  2c815816f8bae6370a15320027c3c09a29dd6c93  https://github.com/JuliaQuantum/JuliaQuantum.github.io/commit/ba62b13c9dbf1e5a0c9e73c87b8ce33c2906bfcd
    - [x] `LICENSE.md` https://github.com/JuliaQuantum/JuliaQuantum.github.io/commit/9c3fdccfe77682ae518a3aeedd533f692e58986e
    - [x] Initialized `index.md` https://github.com/JuliaQuantum/JuliaQuantum.github.io/commit/8f68a6336af801910ba6cbdc4b968be74e580f83
    - [x] Provided some unmature `logo` images and the `favicon.ico` for preview. https://github.com/JuliaQuantum/JuliaQuantum.github.io/commit/08c8399fb4cde528b54021eb6edee29b4180c419  https://github.com/JuliaQuantum/JuliaQuantum.github.io/commit/ceb00a358ef1873b440cf964322ea8f5ea64a317  https://github.com/JuliaQuantum/JuliaQuantum.github.io/commit/21b161cb2fc53248645f88eea15e0f1a3be7b4fe  
    - [x] Redefined `links.html`.  https://github.com/JuliaQuantum/JuliaQuantum.github.io/commit/300c2900cd7b20657d9901646de0ea51f0a7d619

* Beyond the todo list, also finished:
    - [x] Registered a Google account for the org, and set up the Google analysis tool for the website.  https://github.com/JuliaQuantum/JuliaQuantum.github.io/commit/08c8399fb4cde528b54021eb6edee29b4180c419
    - [x] Set up a Google+ page for JuliaQuantum and custermised some social link buttons as the footer.  https://github.com/JuliaQuantum/JuliaQuantum.github.io/commit/c26859498b6fbe894a8ae189da9095d809894211

Extral task: once the Jekyll page is finally online, we should burn a RSS feed and update the footer. 

You may want to checkout the dev-jekyll branch and suggest improvements.

**Comment by i2000s** [comment]
Listed task finished. Followups will occur on issue #9.

**Comment by jiahao** [comment]
:fireworks:

**Comment by emptymalei** [comment]
**UPDATE**

I figured out recently that GitHub actually can compile a jekyll site from source in `master` branch. This has been tested on my own jekyll site and I believes this is generally true even for Organization Pages.

Here comes my suggestions:

1. **Merge source branch with master branch** and test it out.
2. The source branch can be deprecated as long as the master branch can be automatically compiled by GitHub service.

Well, if it won't work in step 1, just roll back the merge commit.
